### ISSUE TITLE
Cleaning up Upload page UI

### ISSUE THREAD

**Issue by kauberry** [EMSL-MSC/pacifica-uploader#11]

**Comment by GitBytes** [comment]
@kauberry @derekhop 
Not sure this ticket was meant for this kind of notation but see https://github.com/EMSL-MSC/pacifica-uploader/blob/9def901346cc703c42f32c4e9a2187d1ecce8e70/home/templates/home/uploader.html#L27 for one of those things that needs cleaned up and made to work as expected

**Comment by GitBytes** [comment]
Good to go, thanks @derekhop
